UPDATE CATEGORIES
SET
	CATEGORY_NAME = 'Drinks'
WHERE
	CATEGORY_NAME = 'Beverages';

SELECT
	*
FROM
	CATEGORIES;

SELECT
	*
FROM
	SHIPPERS;

INSERT INTO
	SHIPPERS (SHIPPER_ID, COMPANY_NAME, PHONE)
VALUES
	(9, 'USPS', 5232352345);

DELETE FROM SHIPPERS
WHERE
	SHIPPER_ID = 9;

SELECT
	*
FROM
	PRODUCTS;

ALTER TABLE PRODUCTS
DROP CONSTRAINT FK_PRODUCTS_CATEGORIES
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID) ON UPDATE CASCADE ON DELETE CASCADE;

UPDATE CATEGORIES
SET
	CATEGORY_ID = 1001
WHERE
	CATEGORY_ID = 1;

SELECT
	*
FROM
	ORDER_DETAILS;

ALTER TABLE ORDER_DETAILS
DROP CONSTRAINT IF EXISTS FK_ORDER_DETAILS_PRODUCTS
ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ORDER_DETAILS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE;

DELETE FROM CATEGORIES
WHERE
	CATEGORY_ID = 3;

SELECT
	*
FROM
	CUSTOMERS
WHERE
	CUSTOMER_ID = 'VINET';

ALTER TABLE ORDERS
DROP CONSTRAINT IF EXISTS FK_ORDERS_CUSTOMERS
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID) ON UPDATE CASCADE ON DELETE SET NULL;

DELETE FROM CUSTOMERS
WHERE
	CUSTOMER_ID = 'VINET';

SELECT
	*
FROM
	ORDERS
WHERE
	CUSTOMER_ID = 'VINET';

SELECT
	*
FROM
	PRODUCTS
WHERE
	PRODUCT_ID IN (100, 101);

INSERT INTO
	PRODUCTS (
		PRODUCT_ID,
		PRODUCT_NAME,
		QUANTITY_PER_UNIT,
		UNIT_PRICE,
		DISCONTINUED,
		CATEGORY_ID
	)
VALUES
	(100, 'Wheat bread', '1', 13, 0, 5),
	(101, 'White bread', '5 boxes', 13, 0, 5),
	DO UPDATE
SET
	PRODUCT_NAME = EXCLUDED.PRODUCT_NAME,
	QUANTITY_PER_UNIT = EXCLUDED.QUANTITY_PER_UNIT,
	UNIT_PRICE = EXCLUDED.UNIT_PRICE,
	DISCONTINUED = EXCLUDED.DISCONTINUED,
	CATEGORY_ID = EXCLUDED.CATEGORY_ID;

CREATE TEMP TABLE UPDATED_PRODUCT (
	PRODUCTID SMALLINT,
	PRODUCTNAME VARCHAR(50),
	QUANTITYPERUNIT VARCHAR(20),
	UNITPRICE REAL,
	DISCONTINUED BOOLEAN,
	CATEGORYID INT
);

ALTER TABLE UPDATED_PRODUCT
ADD COLUMN DISCONTINUED INT
INSERT INTO
	UPDATED_PRODUCT (
		PRODUCTID,
		PRODUCTNAME,
		QUANTITYPERUNIT,
		UNITPRICE,
		DISCONTINUED,
		CATEGORYID
	)
VALUES
	(100, 'wheat bread', '10', 20, 1, 5),
	(101, 'white bread', '5 Boxes', 19.99, 0, 5),
	(
		102,
		'Midnight Mango Fizz',
		'24 - 12 oz bottles',
		19,
		0,
		1
	),
	(
		103,
		'Savory Fire Sauce',
		'12 - 550 ml bottles',
		10,
		0,
		2
	);

MERGE INTO PRODUCTS P USING UPDATED_PRODUCT UP ON P.PRODUCT_ID = UP.PRODUCTID WHEN MATCHED
AND UP.DISCONTINUED = 1 THEN DELETE WHEN MATCHED
AND UP.DISCONTINUED = 0 THEN
UPDATE
SET
	UNIT_PRICE = UP.UNITPRICE,
	DISCONTINUED = UP.DISCONTINUED WHEN NOT MATCHED
	AND UP.DISCONTINUED = 0 THEN INSERT (
		PRODUCT_ID,
		PRODUCT_NAME,
		QUANTITY_PER_UNIT,
		UNIT_PRICE,
		DISCONTINUED,
		CATEGORY_ID
	)
VALUES
	(
		UP.PRODUCTID,
		UP.PRODUCTNAME,
		UP.QUANTITYPERUNIT,
		UP.UNITPRICE,
		UP.DISCONTINUED,
		UP.CATEGORYID
	);

SELECT
	*
FROM
	PRODUCTS
WHERE
	PRODUCT_ID IN (100, 101, 102, 103);

SELECT
	ORDER_ID,
	(
		EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME
	) AS EMPLOYEE_FULLNAME
FROM
	ORDERS
	INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEE_ID = ORDERS.EMPLOYEE_ID;